const products = [
  { name: "tecno comon 11", price: 240, image: "/images/pic (1).jpg" },
  { name: "tecno comon 11", price: 240, image: "/images/pic (2).jpg" },
  { name: "tecno comon 11", price: 240, image: "/images/pic (3).jpg" },
  { name: "tecno comon 11", price: 240, image: "/images/pic (4).jpg" },
  { name: "tecno comon 11", price: 240, image: "/images/pic (5).jpg" },
  { name: "tecno comon 11", price: 240, image: "/images/pic (6).jpg" },
  { name: "tecno comon 11", price: 240, image: "/images/pic (7).jpg" },
  { name: "tecno comon 11", price: 240, image: "/images/pic (8).jpg" },
  { name: "tecno comon 11", price: 240, image: "/images/pic (9).jpg" },
  { name: "tecno comon 11", price: 240, image: "/images/pic (10).jpg" },
  { name: "tecno comon 11", price: 240, image: "/images/pic (11).jpg" },
  { name: "tecno comon 11", price: 240, image: "/images/pic (12).jpg" },
  { name: "tecno comon 11", price: 240, image: "/images/pic (13).jpg" },
  { name: "tecno comon 11", price: 240, image: "/images/pic (14).jpg" },
  { name: "tecno comon 11", price: 240, image: "/images/pic (15).jpg" },
  { name: "tecno comon 11", price: 240, image: "/images/pic (16).jpg" },
  { name: "tecno comon 11", price: 360, image: "/images/pic (17).jpg" },
  { name: "tecno comon 11", price: 240, image: "/images/pic (18).jpg" },
  { name: "tecno comon 11", price: 240, image: "/images/pic (19).jpg" },
  { name: "tecno comon 11", price: 240, image: "/images/pic (20).jpg" },
  { name: "tecno comon 11", price: 240, image: "/images/pic (21).jpg" },
  { name: "tecno comon 11", price: 240, image: "/images/pic (22).jpg" },
  { name: "tecno comon 11", price: 500, image: "/images/pic (23).jpg" },
  { name: "tecno comon 11", price: 240, image: "/images/pic (24).jpg" },
  { name: "tecno comon 11", price: 240, image: "/images/pic (25).jpg" },
  { name: "tecno comon 11", price: 240, image: "/images/pic (26).jpg" },
  { name: "tecno comon 11", price: 366, image: "/images/pic (27).jpg" },
  { name: "tecno comon 11", price: 240, image: "/images/pic (28).jpg" },
  { name: "tecno comon 11", price: 240, image: "/images/pic (29).jpg" },
  { name: "tecno comon 11", price: 240, image: "/images/pic (30).jpg" },
  { name: "tecno comon 11", price: 240, image: "/images/pic (31).jpg" },
];

export default products;
